---
- name: Obtener el estado de Apache
  hosts: all
  become: true  # Permite ejecutar comandos como root

  tasks:
    - name: Verificar si Apache esta instalado
      command: dpkg -l | grep apache2
      register: apache_installed
      ignore_errors: yes

    - name: Obtener el estado de Apache
      command: systemctl status httpd
      register: apache_status
      when: apache_installed.rc == 0

    - name: Mostrar el estado de Apache
      debug:
        var: apache_status.stdout_lines
      when: apache_installed.rc == 0
